version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: migrationos-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-migrationos}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-migrationos_secure_pass}
      POSTGRES_DB: ${POSTGRES_DB:-migrationos_db}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-migrationos}']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: migrationos-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: migrationos-api
    restart: always
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_PROVIDER: postgresql
      DATABASE_URL: postgresql://${POSTGRES_USER:-migrationos}:${POSTGRES_PASSWORD:-migrationos_secure_pass}@db:5432/${POSTGRES_DB:-migrationos_db}?schema=public
      QUEUE_PROVIDER: redis
      REDIS_URL: redis://redis:6379
      ENCRYPTION_KEY: ${ENCRYPTION_KEY:-change_this_to_a_secure_32_character_key_in_prod}
    ports:
      - '4000:4000'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: migrationos-web
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3000
      NEXT_PUBLIC_API_URL: http://localhost:4000
    ports:
      - '3000:3000'
    depends_on:
      - api

volumes:
  postgres_data:
  redis_data:
